(LENGTH '(OPEN THE POD BAY DOORS HAL))  ;; length 6

(LENGTH '((OPEN) (THE POD BAY DOORS) HAL))  ;; length 3

(LENGTH '((1 2 3) (4 5 6) (7 8 9) (10 11 12)))  ;; length 4

(LENGTH '((ONE) FOR ALL (AND (TWO (FOR ME)))))  ;; length 4

(LENGTH '((Q SPADES)
	  (7 HEARTS)
	  (6 CLUBS)
	  (5 DIAMONDS)
	  (2 DIAMONDS)))  ;; length 5

(LENGTH '((PENNSYLVANIA (THE KEYSTONE STATE))
	  (NEW-JERSEY (THE GARDEN STATE))
	  (MASSACHUSETTS (THE BAY STATE))
	  (FLORIDA (THE SUNSHINE STATE))
	  (NEW-YORK (THE EMPIRE STATE))
	  (INDIANA (THE HOOSIER STATE))))  ;; length 6
